// Regenerates src/components/iconPaths.ts from @material-design-icons/svg.
//
// Icon choices mirror sing-box-for-android (Compose Material Icons): the
// style key below matches Icons.Default/Filled ("filled") vs Icons.Outlined
// ("outlined") used there for the same feature.
import { readFileSync, writeFileSync } from "node:fs";

const ICONS = {
  // navigation (NavigationDestinations.kt)
  dashboard: "filled",
  text_snippet: "filled",
  folder: "filled",
  swap_vert: "filled",
  terminal: "filled",
  settings: "filled",
  // dashboard cards
  upload: "outlined",
  download: "outlined",
  cable: "outlined",
  tune: "outlined",
  route: "outlined",
  bug_report: "outlined",
  // groups
  speed: "filled",
  unfold_more: "filled",
  // logs
  filter_list: "filled",
  save: "filled",
  share: "filled",
  delete: "filled",
  content_copy: "filled",
  pause: "filled",
  play_arrow: "filled",
  // tools
  network_check: "outlined",
  swap_horiz: "filled",
  hub: "outlined",
  stop: "filled",
  logout: "filled",
  warning_amber: "outlined",
  // connection error
  cloud_off: "outlined",
  // chrome
  search: "filled",
  close: "filled",
  check: "filled",
  add: "filled",
  more_vert: "filled",
  expand_more: "filled",
  expand_less: "filled",
  keyboard_arrow_right: "filled",
  arrow_back: "filled",
  drag_handle: "filled",
  menu: "filled",
  dns: "filled",
  // theme picker
  brightness_auto: "filled",
  light_mode: "filled",
  dark_mode: "filled",
  // language picker
  language: "filled",
};

const out = ["// Generated by scripts/gen-icons.mjs — do not edit by hand.",
  "// Icon artwork: Material Design Icons (@material-design-icons/svg), Apache-2.0.",
  "export const ICON_PATHS = {"];

for (const [name, style] of Object.entries(ICONS)) {
  const svg = readFileSync(
    new URL(`../node_modules/@material-design-icons/svg/${style}/${name}.svg`, import.meta.url),
    "utf8",
  );
  const paths = [...svg.matchAll(/<path([^>]*)\/>/g)]
    .filter(([, attrs]) => !attrs.includes('fill="none"'))
    .map(([, attrs]) => attrs.match(/ d="([^"]+)"/)?.[1])
    .filter(Boolean);
  if (paths.length === 0) throw new Error(`no path data in ${style}/${name}.svg`);
  out.push(`  ${name}: ${JSON.stringify(paths.join(" "))},`);
}

out.push("} as const;", "", "export type IconName = keyof typeof ICON_PATHS;", "");
writeFileSync(new URL("../src/components/iconPaths.ts", import.meta.url), out.join("\n"));
console.log(`wrote ${Object.keys(ICONS).length} icons`);
